# Generated by Django 4.1.2 on 2022-10-06 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_book_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='name',
        ),
    ]
