# Generated by Django 4.1.2 on 2022-10-06 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_remove_book_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='price',
        ),
    ]
