# Generated by Django 4.1.2 on 2022-10-06 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_remove_book_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author_name',
        ),
        migrations.RemoveField(
            model_name='book',
            name='description',
        ),
    ]
